fileEncoding: utf-8
environments:
    dev:
        url: http://dev.bar.com
        name: Developer Setup
    prod:
        url: http://foo.bar.com
        name: My Cool App
        
my:
   servers:
       - dev.bar.com
       - foo.bar.com